# Generated by Django 4.2.3 on 2023-07-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=20)),
                ('days_delivery', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.city_id')),
            ],
        ),
    ]
