# Generated by Django 4.2.3 on 2023-07-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_description', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.client')),
            ],
        ),
        migrations.CreateModel(
            name='step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_step', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='buy_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_step_beg', models.DateField()),
                ('buy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.buy')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.step')),
            ],
        ),
        migrations.CreateModel(
            name='buy_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book')),
                ('buy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.buy')),
            ],
        ),
    ]
